### ISSUE TITLE
Error when running `pulp test`

### ISSUE THREAD

**Issue by pallix** [archaeron/purescript-yaml#4]
I got an error when running `pulp test` on my project, when using `purescript-yaml`:

```
* Running tests...
module.js:471
    throw err;
    ^

Error: Cannot find module 'js-yaml'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/user/projects/argumentation/purescript-argumentation/output/Data.YAML.Foreign.Encode/foreign.js:5:12)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
* ERROR: Subcommand terminated with exit code 1
```

**Comment by pallix** [comment]
It seems installing `js-yaml` globally solves the problem?!

**Comment by dgendill** [comment]
It should also work if you just run `npm install` locally in your project.  I've added some documentation on my fork [dgendill/purescript-yaml](https://github.com/dgendill/purescript-yaml).
